# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-15 14:03
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Air',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.BooleanField(default=False)),
                ('value', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(16), django.core.validators.MaxValueValidator(30)])),
                ('room', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Light',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.BooleanField(default=False)),
                ('value', models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(100)])),
                ('room', models.CharField(max_length=50)),
            ],
        ),
    ]
